export const EXAMPLES = [
    {"text": "¿Cómo describirías tu nivel de habilidades en el desarrollo frontend?", "label": "conocimientos"}, 
    {"text": "¿Qué herramientas y lenguajes de programación dominas?", "label": "conocimientos"}, 
    {"text": "¿Qué frameworks de desarrollo frontend has utilizado?", "label": "conocimientos"}, 
    {"text": "¿Cómo te mantienes actualizado en cuanto a las tendencias y novedades en el desarrollo frontend?", "label": "conocimientos"}, 
    {"text": "¿Tienes experiencia en la creación de animaciones y transiciones en CSS? ", "label": "conocimientos"}, 
    {"text": "¿Qué tipo de proyectos has desarrollado hasta ahora?", "label": "experiencia"},
    {"text": "¿Has trabajado en equipo en algún proyecto anteriormente? ", "label": "experiencia"}, 
    {"text": "¿Cómo describirías tu proceso de trabajo para llevar a cabo un proyecto? ", "label": "experiencia"}, 
    {"text": "¿Cómo manejas los errores y problemas que surgen durante el proceso de desarrollo?", "label": "experiencia"}, 
    {"text": "¿Tienes experiencia con la integración de APIs de terceros en tus proyectos? ", "label": "experiencia"}, {"text": "¿Cuáles son tus objetivos a corto y largo plazo como desarrollador frontend?", "label": "objetivos"}, 
    {"text": "¿Qué te motiva a seguir aprendiendo y desarrollándote en este campo? ", "label": "objetivos"}, 
    {"text": "¿Qué tipo de proyectos te gustaría trabajar en el futuro?", "label": "objetivos"}, {"text": "¿Qué te hace destacar como candidato en un puesto de trabajo en el área de desarrollo frontend? ", "label": "objetivos"}, 
    {"text": "¿Qué esperas aprender en un posible trabajo en el área de desarrollo frontend? ", "label": "objetivos"}, 
    {"text": "¿Qué estás estudiando actualmente en la universidad? ", "label": "formacion"}, 
    {"text": "¿Cómo aplicas los conocimientos que adquieres de manera autodidacta en tu formación académica? ", "label": "formacion"}, 
    {"text": "¿Has realizado algún curso o capacitación en el área de desarrollo frontend?", "label": "formacion"}, 
    {"text": "¿Cómo te ha ayudado tu formación académica en tu desarrollo como desarrollador frontend?", "label": "formacion"}, 
    {"text": "¿Cómo has aplicado los conocimientos adquiridos en la universidad en tus proyectos personales?", "label": "formacion"}, {"text": "¿Cómo te pueden contactar en caso de estar interesado en tu perfil?", "label": "contacto"}, 
    {"text": "¿Tienes algún perfil en redes sociales o página web donde se puedan ver tus proyectos?", "label": "contacto"}, 
    {"text": "¿Cuál es tu correo electrónico?", "label": "contacto"}, {"text": "¿Estás disponible para trabajar en proyectos remotos?", "label": "contacto"}, 
    {"text": "¿Cuál es tu disponibilidad para iniciar un trabajo en el área de desarrollo frontend?", "label": "contacto"}, 
    {"text": "Hola", "label": "intro"}, 
    {"text": "Como estás?", "label": "intro"}, 
    {"text": "Quien sos?", "label": "intro"}, 
    {"text": "¿Cuál es el origen de la vida en la Tierra?", "label": "no_relacionadas"}, 
    {"text": "¿Cuál es la mejor forma de cocinar una langosta?", "label": "no_relacionadas"}, 
    {"text": "¿Por qué algunos animales hibernan y otros no?", "label": "no_relacionadas"}, 
    {"text": "¿Cuánto tiempo tarda la luz del sol en llegar a la Tierra?", "label": "no_relacionadas"}, 
    {"text": "¿Cuál es la montaña más alta del mundo", "label": "no_relacionadas"}, 
    {"text": "¿Qué lenguajes sabés?", "label": "conocimientos"}, 
    {"text": "¿Qué tecnologías manejas?", "label": "conocimientos"}, 
    {"text": "¿sabes ingles?", "label": "conocimientos"},
    {"text": "donde trabajaste?", "label": "experiencia"},
    {"text": "ayuda", "label": "ayuda"},
    {"text": "necesito asistencia", "label": "ayuda"},
    {"text": "1", "label": "conocimientos"},
    {"text": "2", "label": "objetivos"},
    {"text": "3", "label": "formacion"}
]